<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [6]:
import os

In [7]:
datos = os.listdir()
datos

['.DS_Store',
 'modulo2-leccion02-pandas-basicos copy.ipynb',
 'Prueba_arrays.ipynb',
 'filtrado_array.ipynb',
 'laboratorio-modulo1-leccion01-manejo-errores.ipynb',
 'pruebas_pandas.ipynb',
 'mi_repaso_sentencias_control.ipynb',
 'laboratorio-modulo1-leccion01-break-pass-continue.ipynb',
 'laboratorio-modulo1-leccion02-clases.ipynb',
 'laboratorio-modulo2-leccion01-numpy copy.ipynb',
 'mi_repaso_dict.ipynb',
 '.git']

In [8]:
diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}

diccioanrio_df = {}
for i in datos:
    df = pd.read_csv(i)
    diccioanrio_df[i.spl]


<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/var/folders/r4/jsr6jl3d5js8g1ztlswntdr80000gp/T/ipykernel_4290/1996085454.py:1: SyntaxWarning: invalid escape sequence '\d'
  diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}


NameError: name 'diccioanrio_df' is not defined

for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [2]:
import numpy as np

In [3]:
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [4]:
array_2d = array_1d.reshape(2, 5)

print(array_2d)

print(f"Este es el número de filas y columnas que tiene el nuevo array: {array_2d.shape}")

print(f"El nuevo array tiene {array_2d.ndim} dimensiones")

[[0 1 2 3 4]
 [5 6 7 8 9]]
Este es el número de filas y columnas que tiene el nuevo array: (2, 5)
El nuevo array tiene 2 dimensiones


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [5]:
lista_ceros = [0, 2, 0, 3, 0, 4, 0]

array_ceros = np.array(lista_ceros)

print(f"El array que vamos a utilizar es el siguiente: {array_ceros}")

print(f"Estos son los índices que contienen valores distintos de 0: {np.nonzero(array_ceros)}")

El array que vamos a utilizar es el siguiente: [0 2 0 3 0 4 0]
Estos son los índices que contienen valores distintos de 0: (array([1, 3, 5]),)


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [6]:
array_3d = np.random.random_sample((3, 3))
print(array_3d)

[[0.24668957 0.72716415 0.02789609]
 [0.85081964 0.4513202  0.84363955]
 [0.3582661  0.28384928 0.39888747]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [7]:
array_min_max = np.random.randint(0, 100, (2, 5))
print(array_min_max)

valor_max = np.max(array_min_max)
valor_min = np.min(array_min_max)

print(f"El valor máximo del array es {valor_max}")
print(f"El valor mínimo del array es {valor_min}")


[[82 93  7 57 56]
 [87 70 50 13 67]]
El valor máximo del array es 93
El valor mínimo del array es 7


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [8]:
array_normal = np.arange(10)
print(f"Este es el array original{array_normal}")
print(array_normal.ndim)

array_invertido = array_normal[::-1]
print(f"Este es el array ivnvertido{array_invertido}")

Este es el array original[0 1 2 3 4 5 6 7 8 9]
1
Este es el array ivnvertido[9 8 7 6 5 4 3 2 1 0]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [9]:
array_tridi = np.random.randint(1, 25, (2, 3, 4))
print(array_tridi)

[[[18  5 16 15]
  [19 22  4 18]
  [19 12  4 24]]

 [[19 24 23  5]
  [23  8  2 24]
  [13  1  9  7]]]


In [10]:
print(array_tridi.ndim)

3


In [11]:
print(f"El primero 15 que aparece es el siguiente: {array_tridi[1, 0, 2]}")
print(f"El primer array completo es: {array_tridi[0, ::]}")
print(f"La útlima fila del útlimo es array es: {array_tridi[1, 2, :]}")

El primero 15 que aparece es el siguiente: 23
El primer array completo es: [[18  5 16 15]
 [19 22  4 18]
 [19 12  4 24]]
La útlima fila del útlimo es array es: [13  1  9  7]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [12]:
array_tri_1_30 = np.random.randint(1, 31, (3, 2, 5))
print(array_tri_1_30)

[[[23 18  4 15 25]
  [10 24 15 24 28]]

 [[22 25  3 12  4]
  [26  7 10 28 20]]

 [[ 7 23  3 14  8]
  [24  7 17  6 22]]]


In [13]:
print(array_tri_1_30[0, :, :2 ])

[[23 18]
 [10 24]]


In [14]:
print(array_tri_1_30[1:, :, :])

[[[22 25  3 12  4]
  [26  7 10 28 20]]

 [[ 7 23  3 14  8]
  [24  7 17  6 22]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [15]:
array_432 = np.random.randint(1, 25, (4, 3, 2))
print(array_432)

[[[16 17]
  [10 24]
  [23 13]]

 [[22  4]
  [22 22]
  [15 16]]

 [[12 22]
  [ 9 11]
  [15 13]]

 [[ 2  4]
  [14 14]
  [ 5 19]]]


In [16]:
array_432[1, 1, :]= 0
print(array_432)

[[[16 17]
  [10 24]
  [23 13]]

 [[22  4]
  [ 0  0]
  [15 16]]

 [[12 22]
  [ 9 11]
  [15 13]]

 [[ 2  4]
  [14 14]
  [ 5 19]]]


In [17]:
array_432[3, :, :] = -1
print(array_432)

[[[16 17]
  [10 24]
  [23 13]]

 [[22  4]
  [ 0  0]
  [15 16]]

 [[12 22]
  [ 9 11]
  [15 13]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [18]:
array_243 = np.random.randint(-10, 13, (2, 4, 3))
print(array_243)

[[[ -6   6  -4]
  [ -5  11   2]
  [  1  -9   3]
  [ -1  -6  -5]]

 [[-10  11   2]
  [ -2   7  -2]
  [  6  -5   5]
  [ 10  -1  -4]]]


In [19]:
elementos = 5

print(array_243[array_243 > elementos])


[ 6 11 11  7  6 10]


In [20]:
resultado = np.where(array_243 < 0, 0, array_243)
print(resultado)

[[[ 0  6  0]
  [ 0 11  2]
  [ 1  0  3]
  [ 0  0  0]]

 [[ 0 11  2]
  [ 0  7  0]
  [ 6  0  5]
  [10  0  0]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [36]:
array_333 = np.random.randint(1, 28, (3, 3, 3))
print(array_333)

[[[25 12 20]
  [ 9  3  4]
  [ 8 19  5]]

 [[11 25 11]
  [17  5  9]
  [14  9 17]]

 [[22 18  4]
  [ 5  4 21]
  [21  3 16]]]


In [37]:
subarray1 = array_333[1, :, :2]
print(subarray1)

[[11 25]
 [17  5]
 [14  9]]


In [41]:
filtro1 = array_333[2, :, :]
elementos2 = np.where(filtro1 > 20)
valores_mayor_20 = filtro1[elementos2]
print(valores_mayor_20)

[22 21 21]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [46]:
array_aleatorio = np.random.randint(1, 100, (2, 5))
print(array_aleatorio)

[[66 79 99 66 23]
 [19 21  4 76 28]]


In [21]:
max_value = np.max(array_aleatorio)
min_value = np.min(array_aleatorio)

max_index = np.where(array_aleatorio == max_value)
min_index = np.where(array_aleatorio == min_value)

array_aleatorio[max_index[0]] = 0
array_aleatorio[min_index[0]] = 0

print(array_aleatorio)

NameError: name 'array_aleatorio' is not defined

#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [22]:
array15 = np.random.randint(1, 101,(3, 5))
print(f"Este es el array original {array15}")

array_ascendente = np.sort(array15)
print(f"Este es el array ordenado en orden ascendente {array_ascendente}")

Este es el array original [[51 86 99 44  5]
 [89 89 16 83  5]
 [30 56 55 73 92]]
Este es el array ordenado en orden ascendente [[ 5 44 51 86 99]
 [ 5 16 83 89 89]
 [30 55 56 73 92]]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [33]:
array_4_4 = np.random.randint(1, 100,(4, 4))
print(array_4_4)

suma_filas = array_4_4.sum(axis=1)
print(f"El resultado de la suma de las filas es: {suma_filas}")

[[65 99 55 28]
 [ 8 60 21  8]
 [28 88 34 40]
 [78 97 67 21]]
El resultado de la suma de las filas es: [247  97 190 263]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [34]:
array_random = np.random.randint(1, 11, (2, 5))
print(array_random)

[[ 4 10  6  1  9]
 [ 6  4  1  7  2]]


In [38]:
media_array = array_random.mean()
print(f"La media de mi array es: {media_array}")

desv_est_array = array_random.std()
print(f"La desviación estándar en mi array es: {desv_est_array}")

La media de mi array es: 5.0
La desviación estándar en mi array es: 3.0


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [48]:
array_transpose = np.random.randint(1, 25, (2, 3, 4))
print(array_transpose)
print(f"Este array tiene {array_transpose.ndim} dimensiones")
print({array_transpose.shape})

[[[ 6 18 18 14]
  [24 23 24  6]
  [ 6 17  1  9]]

 [[ 5 18  2  2]
  [20 13  1 15]
  [ 3 16 10 12]]]
Este array tiene 3 dimensiones
{(2, 3, 4)}


In [49]:
array_transpuesto = array_transpose.T
print(array_transpuesto)
print(array_transpuesto.shape)

[[[ 6  5]
  [24 20]
  [ 6  3]]

 [[18 18]
  [23 13]
  [17 16]]

 [[18  2]
  [24  1]
  [ 1 10]]

 [[14  2]
  [ 6 15]
  [ 9 12]]]
(4, 3, 2)


## Explicación
En este caso hemos cambiado de 2 a 4 dimensiones, el número de columnas también ha cambiado a ser de 4 a 2. El número de filas no ha cambiado ya que se encuentra en el centro y es respecto al cual 'pivota' el array al utilizar la función 'T'

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [45]:
array_swap_original = np.random.randint(1, 25, (3, 4, 2))
print(array_swap_original)
print(f"EL array tiene {array_swap_original.ndim} dimensiones")
print(f"Las dimensiones son {array_swap_original.shape}")

[[[ 6  2]
  [ 7 16]
  [18 19]
  [ 3  6]]

 [[ 1 12]
  [10  4]
  [21 18]
  [16  5]]

 [[18  2]
  [ 8  8]
  [ 3 23]
  [ 7 10]]]
EL array tiene 3 dimensiones
Las dimensiones son (3, 4, 2)


In [46]:
array_swap = np.swapaxes(array_swap_original, 0, 1)
print(array_swap)
print(f"El array nuevo tiene {array_swap.ndim} dimensiones")
print(f"Las dimensiones del nuevo array son {array_swap.shape}")

[[[ 6  2]
  [ 1 12]
  [18  2]]

 [[ 7 16]
  [10  4]
  [ 8  8]]

 [[18 19]
  [21 18]
  [ 3 23]]

 [[ 3  6]
  [16  5]
  [ 7 10]]]
El array nuevo tiene 3 dimensiones
Las dimensiones del nuevo array son (4, 3, 2)


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [47]:
array_rotacion = np.random.randint(1, 25, (3, 2, 4))
print(array_rotacion)
print(f"El array tiene {array_rotacion.ndim} dimensiones")
print(f"Las dimensiones son {array_rotacion.shape}")

[[[15 23 14 10]
  [ 9  9 13  7]]

 [[ 6 23 23  4]
  [ 2 19 21  9]]

 [[21  5 17 19]
  [ 1 24 16 19]]]
El array tiene 3 dimensiones
Las dimensiones son (3, 2, 4)


In [51]:
array_360 = np.swapaxes(array_rotacion, 0, 1)
array_360 = np.swapaxes(array_360, 0, 2 )
print(array_360)
print(f"El array rotado tiene {array_360.ndim}")
print(f"Las dimensiones del array rotado son {array_360.shape}")

[[[15  9]
  [ 6  2]
  [21  1]]

 [[23  9]
  [23 19]
  [ 5 24]]

 [[14 13]
  [23 21]
  [17 16]]

 [[10  7]
  [ 4  9]
  [19 19]]]
El array rotado tiene 3
Las dimensiones del array rotado son (4, 3, 2)


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.